
USE [master]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [geradorTesteDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [geradorTesteDb] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [geradorTesteDb] SET ANSI_NULLS OFF
GO

ALTER DATABASE [geradorTesteDb] SET ANSI_PADDING OFF
GO

ALTER DATABASE [geradorTesteDb] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [geradorTesteDb] SET ARITHABORT OFF
GO

ALTER DATABASE [geradorTesteDb] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [geradorTesteDb] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [geradorTesteDb] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [geradorTesteDb] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [geradorTesteDb] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [geradorTesteDb] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [geradorTesteDb] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [geradorTesteDb] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [geradorTesteDb] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [geradorTesteDb] SET  DISABLE_BROKER
GO

ALTER DATABASE [geradorTesteDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [geradorTesteDb] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [geradorTesteDb] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [geradorTesteDb] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [geradorTesteDb] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [geradorTesteDb] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [geradorTesteDb] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [geradorTesteDb] SET RECOVERY SIMPLE
GO

ALTER DATABASE [geradorTesteDb] SET  MULTI_USER
GO

ALTER DATABASE [geradorTesteDb] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [geradorTesteDb] SET DB_CHAINING OFF
GO

ALTER DATABASE [geradorTesteDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [geradorTesteDb] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [geradorTesteDb] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [geradorTesteDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [geradorTesteDb] SET  READ_WRITE
GO


/****** Object:  Database [geradorTesteDb]    Script Date: 31/05/2022 11:19:08 ******/
CREATE DATABASE [geradorTesteDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'geradorTesteDb', FILENAME = N'C:\Users\Carlos Daniel\geradorTesteDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'geradorTesteDb_log', FILENAME = N'C:\Users\Carlos Daniel\geradorTesteDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT

GO

--Syntax Error: Expected DEFAULT_FULLTEXT_LANGUAGE but encountered CATALOG_COLLATION instead.
--
--/****** Object:  Database [geradorTesteDb]    Script Date: 31/05/2022 11:19:08 ******/
--CREATE DATABASE [geradorTesteDb]
-- CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'geradorTesteDb', FILENAME = N'C:\Users\Carlos Daniel\geradorTesteDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG ON 
--( NAME = N'geradorTesteDb_log', FILENAME = N'C:\Users\Carlos Daniel\geradorTesteDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
-- WITH CATALOG_COLLATION = DATABASE_DEFAULT

GO


ALTER DATABASE [geradorTesteDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  

GO

--Syntax Error: Incorrect syntax near ACCELERATED_DATABASE_RECOVERY.
--
--ALTER DATABASE [geradorTesteDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  



GO
